#pragma once

#include "TimeCoordinate.h"
#include <cstdint>
#include <vector>
#include <algorithm>
#include <juce_core/juce_core.h>

namespace OpenTune {

struct VocalSegment {
    uint64_t id{0};
    int64_t startTick{0};
    int64_t endTick{0};
    float gainLinear{1.0f};
    float tension01{0.5f};
    uint32_t flags{0};
    juce::String label;

    static constexpr uint32_t kFlagAutoGenerated = 1u << 0;

    double getStartClipSeconds() const { return TimeCoordinate::clipTickToSeconds(startTick); }
    double getEndClipSeconds() const { return TimeCoordinate::clipTickToSeconds(endTick); }
    void setStartClipSeconds(double sec) { startTick = TimeCoordinate::clipSecondsToTick(sec); }
    void setEndClipSeconds(double sec) { endTick = TimeCoordinate::clipSecondsToTick(sec); }
};

class VocalSegmentSequence {
public:
    const std::vector<VocalSegment>& getSegments() const noexcept { return segments_; }
    std::vector<VocalSegment>& getSegments() noexcept { return segments_; }

    void sortAndValidate(double clipDurationSec);
    /** Returns false and sets errOut if invalid or cannot move (locked neighbors handled by caller). */
    bool moveBoundary(uint64_t segmentId, bool isLeftEdge, double newSec, double clipDurationSec,
                      double minSegmentSec, juce::String& errOut);

    void insertSegment(VocalSegment seg);
    bool eraseById(uint64_t id);
    bool mergeAdjacent(uint64_t leftId, juce::String& errOut);
    bool splitAtTime(uint64_t segmentId, double splitSec, juce::String& errOut);

    VocalSegment* findById(uint64_t id);
    const VocalSegment* findById(uint64_t id) const;

    uint64_t allocateId();

    /** Reassign ids 1..n in order (after merging clips). */
    void reassignSequentialIds();

private:
    std::vector<VocalSegment> segments_;
    uint64_t nextId_{1};
};

} // namespace OpenTune
